syntax on
set shortmess+=I
set incsearch
set ignorecase
set smartcase
set wildmode=list:longest
set virtualedit=onemore
set history=1000
set scrolloff=4
set tabstop=4
set shiftwidth=4
set expandtab
set hlsearch
set nu
set cursorline
cabbrev W w !sudo tee % > /dev/null<CR>:e!<CR><CR>
map <F2> :set hls!<CR>
map <F3> :set nu!<CR>
map <F4> :set list!<CR>


set nocompatible              " be iMproved
filetype off                  " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'jpo/vim-railscasts-theme'
Bundle 'bling/vim-airline'
Bundle 'scrooloose/syntastic'
Bundle 'davidhalter/jedi-vim'
Bundle 'guns/vim-clojure-static'
Bundle 'jnwhiteh/vim-golang'

filetype plugin indent on     " required!

colorscheme railscasts

let g:airline#extensions#tabline#enabled = 1
set laststatus=2

let g:syntastic_python_checkers=['pylint']
let g:syntastic_go_checkers=['go', 'gofmt']

let g:jedi#popup_on_dot = 0
